// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/helloWorld/index.vue')['default'];
    MyHeader: typeof import('./src/components/myHeader/my-header.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    VanButton: typeof import('vant/es')['Button'];
    VanPopup: typeof import('vant/es')['Popup'];
  }
}
